blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ Soporte General
    url: https://github.com/donchelo/orderLoaderUI/discussions
    about: Para preguntas generales y discusiones sobre el proyecto
  - name: ğŸ“š DocumentaciÃ³n
    url: https://github.com/donchelo/orderLoaderUI/tree/master/docs
    about: Revisa la documentaciÃ³n del proyecto